### ISSUE TITLE
Error after install

### ISSUE THREAD

**Issue by PubliAlex** [chkilel/icones-plugin#2]
Hello,

After installing this module (using composer), I get an error : 

![image](https://user-images.githubusercontent.com/55833027/154646481-e0fcab75-8e52-4da7-b93d-7f22bfa5173a.png)

Best regards,

**Comment by PubliAlex** [comment]
Any news about it ? Is the module still maintained ?

**Comment by chkilel** [comment]
Hello @PubliAlex, 
I'm sorry to let you waiting, I updated the plugin and fixed some bugs related to the package dependency.
Please check and confirm if it works as expected.
Thanks for reporting.
Regards

**Comment by PubliAlex** [comment]
Hello,

Still have the error, when I try to install the plugin and run `php artisan october:migrate`

I get this error

![image](https://user-images.githubusercontent.com/55833027/156746134-f34124ef-3ee2-4c38-aa39-ce3a09821bf2.png)

Best regards,

**Comment by chkilel** [comment]
Freeze lib dependency iconify/json to version 1 
A recent change in the iconify/json iconset format cause an issue, will be addressed in v2 of the Plugin
